# Generated by Django 2.1.7 on 2019-02-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontenmentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('pengalaman', models.CharField(max_length=255)),
                ('komentar', models.TextField(max_length=255)),
                ('gambar', models.CharField(max_length=255)),
            ],
        ),
    ]
