# Generated by Django 2.1.7 on 2019-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KontenBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.CharField(max_length=255)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(default='', max_length=255)),
            ],
        ),
    ]
