# Generated by Django 2.1.7 on 2019-02-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontenblog',
            name='deskripsi',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
