# Generated by Django 2.1.7 on 2019-02-14 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posting_jadwal_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('videolink', models.TextField(max_length=5000)),
                ('jadwal_publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
