# Generated by Django 2.1.7 on 2019-02-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190214_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='namaauthor',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
