# Generated by Django 2.1.7 on 2019-02-15 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_posting_namaauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('komentar', models.TextField(max_length=5000)),
                ('jadwal_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('statuspublih', models.BooleanField(default=True)),
            ],
        ),
    ]
