# Generated by Django 2.1.7 on 2019-02-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mainpage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Posting'),
        ),
    ]
