# Generated by Django 2.1.7 on 2019-02-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190215_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parents',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
