# Generated by Django 2.1.7 on 2019-02-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190215_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parents',
        ),
        migrations.AlterField(
            model_name='comment',
            name='mainpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Posting'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='Imagen'),
        ),
    ]
