# Generated by Django 2.1.7 on 2019-02-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_auto_20190214_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontenblog',
            old_name='deskripsi1',
            new_name='deskripsi6',
        ),
    ]
